# Generated by Django 5.1.3 on 2024-12-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='default_imsge.jpg', upload_to='food_images'),
        ),
    ]
